### ISSUE TITLE
look your GAS file, i have a question，any suggest will thanks very much

### ISSUE THREAD

**Issue by EternityPOI** [vorixo/devtricks#1]
When the game has such a demand，from character A possess to character B, other guy attack character A(at this time character no player controller), attack try active a skill in a character A(skill is a GA, local predicted), because character no player controller ,cause GA no active, like this demand(try active GA,but no player controller), character own ASC, or player state own ASC, Can't solve this requirement，any suggest will thanks very much，email: 2320305523@qq.com

**Comment by vorixo** [comment]
Hello, it depends a lot about the game requirements. These are two ideas that you can implement. Might want to consult it with your game designer:

- Ignore damage if conditions aren't met
- Implement an event buffer that will queue-up events until the conditions are met. Then once met, the queue is consumed in a FIFO manner.

**Comment by EternityPOI** [comment]
thank you suggest.
