### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by CoolOppo** [vorixo/devtricks#2]
Is there any way you could put a date on the articles you post (and perhaps an updated date so people know things aren't outdated?)

Helps to know when something was written, could be useful years down the line.

Very nice work though, love the info you have on your site, it's insanely useful and I wish there were more sites like it! (Maybe as a side note you could put a page with links to other useful sites!)

**Comment by vorixo** [comment]
Hey, sorry for the late reply, just saw this!

At the bottom of every article you have an "Updated" field with information on what the article was last updated.
